
name: blog-deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # submodules: true


      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true


      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: build blog
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run build
          > .vuepress/dist/.nojekyll

      - name: deploy blog
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .vuepress/dist

